### ISSUE TITLE
store the pipelinerun in the long-term storage

### ISSUE THREAD

**Issue by vbehar** [jenkins-x-plugins/jx-build-controller#13]
related to https://github.com/jenkins-x/jx-pipelines-visualizer/issues/54 : when we try to render the pipeline and logs for a pipelinerun that has been garbage-collected... well, we can't, because we have no information (except for the pipelinerun name and its namespace).

we could ensure links always work by storing the pipelineruns in the long-term storage, alongside the logs - similar to #11 for the pipelineactivities.

the main difference is that we can't use the standard layout of `jenkins-x/logs/owner/repository/branch/build.log`, because the pipelines-visualizer doesn't know the owner/repo/branch/build - only the pr name and ns.
so maybe we could store the pipelineruns under `jenkins-x/logs/namespace/name.yaml`? or `jenkins-x/pipelineruns/namespace/name.yaml`?

@jstrachan what do you think?

**Comment by Mehdi-Mameri** [comment]
Hello

Just a question, why you can't use the gh-pages branch that have all repositories with jx imported and he store all the build logs ?

Maybe if I don't have a storage for log I can use gh-pages branch of my repos to take the log and see into visualizer

What do you think ?

Greetings

**Comment by vbehar** [comment]
yes, long-term storage can be implemented by a GCS/S3/... bucket, or a git repo in a specific branch, or anything else.
in jx v2 I think github pages was supported (I never used it), but in v3 for the moment the only implementation is the bucket.
maybe it should be an issue on its own?
