### ISSUE TITLE
support for other git providers

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x-plugins/jx-build-controller#6]
There is an issue with: https://github.com/jenkins-x-plugins/jx-build-controller
`GIT_SECRET_SERVER`  is used internally to know which server to clone jx-requirements from but the env variable is never set and there is no way to set it in the helm chart.
it should be set to in my case to `gitlab.com`  I guess we could add this to the deployment in the helm chart but I think it's cleaner to fix requirements.go in jx-helpers to load and write info correctly to `$XDG_CONFIG_HOME/git/credentials`
@jstrachan  what do you think.

**Comment by rawlingsj** [comment]
we can add a helm value to set the `GIT_SECRET_SERVER ` which will be added here https://github.com/jenkins-x-plugins/jx-build-controller/blob/859baf6d70bee09acc2122f1c96955ba26e0a52b/charts/jx-build-controller/templates/deployment.yaml#L61

I'll update the version stream to default this today.
